# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
      # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      #   pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_*.py

    - name: Install Ruff
      run: python -m pip install ruff

    - name: Lint code with Ruff
      run: ruff check .

    - name: Check code formatting with Ruff
      run: ruff check --fix --diff
      continue-on-error: true
